### ISSUE TITLE
Commenting frontpage components

### ISSUE THREAD

**Issue by WaiHaiDere** [se701-group6/se701-assignment1#103]
**Is your feature request related to a problem? Please describe.**
As someone picking up this project, I may be confused by the project structure

**Describe the solution you'd like**
Add comments explaining the service/container/page structure

**Describe alternatives you've considered**
Also should to add documentation in the wiki

**Comment by ErnWong** [comment]
I approve

**Comment by timovv** [comment]
I approve

Cheers,
Timo

On Fri, Mar 20, 2020 at 3:54 PM Tyger Kong <notifications@github.com<mailto:notifications@github.com>> wrote:

Assigned #103<https://github.com/se701-group6/se701-assignment1/issues/103> to @timovv<https://github.com/timovv>.

**Comment by FrankWangma** [comment]
I approve, we need to add this.

**Comment by ErnWong** [comment]
Be careful not to get too carried away and add unnecessary comments for the sake of having comments - those add noise to the code and could potentially make the code harder to read.

**Comment by FrankWangma** [comment]
This issue has been resolved with the last 2 PRs
