### ISSUE TITLE
API routes are incorrect

### ISSUE THREAD

**Issue by timovv** [se701-group6/se701-assignment1#106]
As a user, I want API requests to go the right place so that when I want to view posts, they actually show up.

## Expected Behavior
When getting posts, the endpoint to call should be `/api/posts/{id}`.

## Current Behavior
When getting posts using the API, the route is incorrect and it tries to request from `/api/api/posts/{id}`.

## Possible Solution
Update the route so that it points to the correct endpoint.

## Steps to Reproduce

1. Create a post in the frontend
2. Try and open it
3. Observe that it does not work

**Comment by ErnWong** [comment]
I can reproduce. I approve.

**Comment by FrankWangma** [comment]
Same here. Approved

**Comment by GrunWong** [comment]
I approve.
