### ISSUE TITLE
No default pull request template is applied to new pull requests

### ISSUE THREAD

**Issue by ErnWong** [se701-group6/se701-assignment1#13]
## Expected Behavior

Creating a new PR should automatically be populated with the PR template.

## Current Behavior

Right now, the PR template only shows up when you manually append `&template=pull_request_template.md` to the pull request URL.

## Possible Solution

Move `/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md` to `/.github/pull_request_template.md`. The current location is used for multiple pull request templates while the proposed location is used for the default pull request template.

## Steps to Reproduce

1. Open https://github.com/se701-group6/se701-assignment1/compare/master...ErnWong:dummy-branch-for-pr-template-test?expand=1 and notice the blank pull request body
2. Open https://github.com/se701-group6/se701-assignment1/compare/master...ErnWong:dummy-branch-for-pr-template-test?expand=1&template=pull_request_template.md and notice the populated pull request template.

## Context (Environment)

See #1 

## Detailed Description

See above

## Possible Implementation

See above

**Comment by timovv** [comment]
Oops, guess I misread the docs here. I'll move it.
