### ISSUE TITLE
Run linter on the frontend's build step

### ISSUE THREAD

**Issue by ErnWong** [se701-group6/se701-assignment1#24]
**Is your feature request related to a problem? Please describe.**
As a developer, I want my work to be linted for style consistency and for quality during the build step, so that it is harder to accidentally merge defect-containing code into master.

Moreover, I want to apply [airbnb](https://github.com/airbnb/javascript/) coding style which helps reduce a larger range of code defects.

**Describe the solution you'd like**
1. `npm install --save-dev cross-env`
2. Add `cross-env EXTEND_ESLINT=true` flag to the `start`, `build` and `test` commands so that create-react-app's build steps use our provided `.eslintrc` file.
3. Run the [eslint-prettier-airbnb-react](https://github.com/paulolramos/eslint-prettier-airbnb-react) configuration script to configure `prettier` and `airbnb` to work together.
4. Add `npm run lint` command to run `eslint .`
5. Add `npm run lint-fix` command to run `eslint --fix .`
6. Run `npm run lint-fix`
7. Fix remaining linting issues case by case.
8. Remove extraneous `eslintConfig` field in `package.json` since that field is ignored by eslint if the `.eslintrc` file is present.

**Describe alternatives you've considered**
Just sticking to `prettier` rules.

**Additional context**
See #20 and #21.

**Comment by timovv** [comment]
I approve

**Comment by ErnWong** [comment]
Thanks! I reckon one approval is enough since this is part of the initial things we want to set up.

Fixing the linting issues will affect a lot of files though. It may be slightly painful when others try to merge back.

**Comment by ErnWong** [comment]
Would probably be nice to setup the linter for the backend too as part of the test step
