### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by timovv** [se701-group6/se701-assignment1#26]
**Is your feature request related to a problem? Please describe.**

As a potential contributor or developer, I want to know how the repo is set up so I can get started on development quickly. Typically, this is done by looking at the project's README, but the one at the root of the project is blank.

**Describe the solution you'd like**
I want the project's README to describe the project structure and how I can get my development environment set up. While the README in the frontend folder is good, it only describes the frontend.

The new README should:
* Describe the CI setup (maybe including a build passing/failing badge)
* Describe how to get the project running
* Direct me to project documentation (e.g. the wiki and the README in the frontend directory)

**Describe alternatives you've considered**

Other alternatives may include having a 'getting started' page on the wiki, but it would probably be better to have some information in the README since this is the conventional solution. The wiki can go into further depth as required.

**Additional context**
Not applicable.

**Comment by ErnWong** [comment]
I approve.

**Comment by ErnWong** [comment]
Would be nice to show off these *shiny* badges in the README too:

![CI_SERVER](https://github.com/se701-group6/se701-assignment1/workflows/CI_SERVER/badge.svg)
![CD_SERVER](https://github.com/se701-group6/se701-assignment1/workflows/CD_SERVER/badge.svg)
![CI_FRONTEND](https://github.com/se701-group6/se701-assignment1/workflows/CI_FRONTEND/badge.svg)
![CD_FRONTEND](https://github.com/se701-group6/se701-assignment1/workflows/CD_FRONTEND/badge.svg)

(Not all badges are available yet - the workflows need to run once before GitHub detects them it seems)

**Comment by ErnWong** [comment]
> Would be nice to show off these _shiny_ badges in the README too

Maybe not the CI ones because they are just for the PRs (e.g. the CI_SERVER badge is failing, but not because the master branch has problems, but a PR into master branch has problems)
