### ISSUE TITLE
API Specification

### ISSUE THREAD

**Issue by timovv** [se701-group6/se701-assignment1#27]
**Is your feature request related to a problem? Please describe.**

As a developer on the frontend or the backend, I want documentation of what the API should look like. This will help backend developers as they can implement the API following the specification, and frontend developers as they can implement the frontend under the assumption that the specified API will exist.

**Describe the solution you'd like**
An API specification document on the project wiki. This should include information such as:
* Available routes
* Accepted HTTP methods for these routes
* Expected output format for each route
* Expected status codes and possible error statuses for each route

**Describe alternatives you've considered**
Not applicable

**Additional context**
Not applicable

**Comment by timovv** [comment]
This is being worked on at [this wiki page](https://github.com/se701-group6/se701-assignment1/wiki/API).

**Comment by GrunWong** [comment]
The API documentation has been updated and both frontend and backend have made adjustments to reflect it.
