### ISSUE TITLE
Create a cloud DB

### ISSUE THREAD

**Issue by wooneh** [se701-group6/se701-assignment1#29]
**Is your feature request related to a problem? Please describe.**
As a contributor, I want to create a cloud database so that the application can be accessed from anywhere.

**Describe the solution you'd like**
Use MongoDB Atlas to create a database that can be used by the production server.

**Describe alternatives you've considered**
mLab, but it has been acquired by MongoDB Atlas.

**Additional context**
N/A

**Comment by ErnWong** [comment]
- [x] Appropriate
- [x] Dependencies checked
- [x] Not a duplicate

I approve.

**Comment by wooneh** [comment]
MongoDB Atlas is set up and connected to backend server.
