### ISSUE TITLE
Malformed package-lock.json

### ISSUE THREAD

**Issue by wooneh** [se701-group6/se701-assignment1#30]
## Expected Behavior

Running `npm install` results in successful `node_modules` creation

## Current Behavior

Running `npm install` results in error:
![image](https://user-images.githubusercontent.com/21334474/76574998-d8464a00-6522-11ea-9070-f243968dda7c.png)

## Possible Solution

There is a missing line on line 103-104 that results in misaligned brackets. Fix would be to delete `package-lock.json` and re-run `npm install` to re-create the file.

## Steps to Reproduce

1. Run `cd server`
2. Run `npm install`

## Context (Environment)

I am unable to deploy the current build to the cloud since it cannot install the necessary dependencies.

Unable to build and deploy as `npm install` cannot be run successfully.

## Detailed Description

Recreating `package-lock.json` to fix the malformed line

## Possible Implementation

N/A

**Comment by ErnWong** [comment]
I approve

**Comment by timovv** [comment]
I approve
