### ISSUE TITLE
Set up Jest unit tests on the backend

### ISSUE THREAD

**Issue by andrewh318** [se701-group6/se701-assignment1#31]
**Is your feature request related to a problem? Please describe.**
As a contributor, I would like to have unit tests on the backend so that we can ensure all our API's perform their expected functionality before we deploy into production. 

**Describe the solution you'd like**
Set up Jest unit tests in the backend project

**Describe alternatives you've considered**
I have considered alternative test frameworks to Jest. However, Jest comes with presets for MongoDB that allow us to configure an in-memory MongoDB instance. As a result, we don't end up saving test dummy data into our real database. 

**Additional context**
I am prioritizing the completion of this feature as it is blocking the implementation of our API's.

**Comment by ErnWong** [comment]
I approve.
