### ISSUE TITLE
Implement frontpage

### ISSUE THREAD

**Issue by WaiHaiDere** [se701-group6/se701-assignment1#32]
**Describe the solution you'd like**
As a user, I would like to see all the posts on the front page when I land on the website

**Additional context**
Designs to be supplied by @JamesUOA

**Comment by ErnWong** [comment]
Blocked - Depends on partial completion of #15 

Prototyping and investigative work can begin - but be prepared to change a lot of stuff once the designs for this are done.

@JamesUOA feel free to approve this once designs are done, aye. If it's convenient, it'll be nice to upload the designs to the wiki and link to it from here.
