### ISSUE TITLE
Set up linter for the backend

### ISSUE THREAD

**Issue by ErnWong** [se701-group6/se701-assignment1#36]
**Is your feature request related to a problem? Please describe.**
As a developer, I want my work to be linted for style consistency and for quality during the build step, so that it is harder to accidentally merge defect-containing code into master.

**Describe the solution you'd like**
Configure `eslint` and add the `npm run lint/lint-fix` commands similar to the frontend (#24).
For consistency's sake, it'll also use the airbnb style guide and `prettier`.

**Additional context**
I'll try to get this setup quickly, to minimise the conflict the reformatted files will cause when others try to merge their backend code.

**Comment by timovv** [comment]
Hi,

I approve this issue.

Thanks,
Timo
