### ISSUE TITLE
Create REACT component of the createnewpost page

### ISSUE THREAD

**Issue by gcao417** [se701-group6/se701-assignment1#39]
**Is your feature request related to a problem? Please describe.**
As a user, I want a visable interface for creating a post. 

**Additional context**
Reference to #35

**Comment by ErnWong** [comment]
Have a `onSubmit` prop that will be a function that takes `{ title, body }` object as a parameter, to be called when the user presses the submit button.

The `CreatePostContainer` done in #38 will supply this property when it wraps your component.

**Comment by ErnWong** [comment]
The `CreatePostContainer` also passes a string `errorMessage` prop, which is not an empty string when submitting a new post returns an error.

**Comment by anian100** [comment]
There should form validation to check if the title and body is empty - then the submit button should be disabled and a message should appear

**Comment by ErnWong** [comment]
Update: instead of a `CreatePostContainer` component, we now have a `withCreatePostService` HOC. The `errorMessage` prop is now `null` when there is no error, rather than an empty string.

**Comment by ErnWong** [comment]
Whoops, I accidentally closed this. Reopening.

**Comment by ErnWong** [comment]
Update: the `onSubmit` prop is now a function that takes 2 arguments: title and body, rather than a single object `{ title, body }`
