### ISSUE TITLE
Improper configuration of port for deployment

### ISSUE THREAD

**Issue by wooneh** [se701-group6/se701-assignment1#61]
Related to #60 

## Expected Behavior

Server starts successfully and accepts API calls.

## Current Behavior

Fails to start server.
![image](https://user-images.githubusercontent.com/21334474/76743805-128c4180-67d8-11ea-9be4-e9582cbca5ee.png)

## Possible Solution

Heroku exposes a port that the application is supposed to bind with. Any others will not work. Relevant [link](https://help.heroku.com/P1AVPANS/why-is-my-node-js-app-crashing-with-an-r10-error)
Change `const port = 5001;` to `const port = process.env.PORT || 5001;` in `server.js`

## Steps to Reproduce

1. Deploy `server`.
2. Attempt to access the `server`.

## Context (Environment)

The backend server was successfully deployed, however fails to start.

Server fails to start due to improper configuration of port.

## Detailed Description

Server should bind to `process.env.PORT` in production, and to the port manually specified in development.

**Comment by timovv** [comment]
I approve

Cheers,
Timo

**Comment by ErnWong** [comment]
I approve

**Comment by tia365** [comment]
I approve
