### ISSUE TITLE
CORS needs to be enabled to be able to call the backend from the frontend

### ISSUE THREAD

**Issue by WaiHaiDere** [se701-group6/se701-assignment1#69]
## Expected Behavior
CORS should be enabled to allow backend to be called
## Current Behavior
When calling the API from the frontend (Local backend), the api call is blocked by CORS

## Possible Solution
Enable CORS

## Steps to Reproduce
1. Ensure the frontend is calling local backend in the services
    - `fetch()` should be calling `http://localhost:5001/posts`
2. Run both frontend and backend locally
3. If `fetch()` in `frontendService` is calling the local backend, there will be CORS error in browser console. Same situation for creating a post.

**Comment by ErnWong** [comment]
Will this be fixed by the proxy in #64 , since API will be done by sending requests to the frontend server which then forwards the request to the backend?

**Comment by WaiHaiDere** [comment]
> Will this be fixed by the proxy in #64 , since API will be done by sending requests to the frontend server which then forwards the request to the backend?

Is this not something they need to enable in the backend instead?

**Comment by ErnWong** [comment]
> > Will this be fixed by the proxy in #64 , since API will be done by sending requests to the frontend server which then forwards the request to the backend?
> 
> Is this not something they need to enable in the backend instead?

I don't think so? The frontend server hosts the frontend app, and we would be writing our fetch calls to endpoints like `/api/post/...` which will be received by the frontend server, which proxies the request to the backend.

https://create-react-app.dev/docs/proxying-api-requests-in-development/ describes how our proxy setup will avoid CORS in your case with the local development environment.

**Comment by WaiHaiDere** [comment]
> > > Will this be fixed by the proxy in #64 , since API will be done by sending requests to the frontend server which then forwards the request to the backend?
> > 
> > 
> > Is this not something they need to enable in the backend instead?
> 
> I don't think so? The frontend server hosts the frontend app, and we would be writing our fetch calls to endpoints like `/api/post/...` which will be received by the frontend server, which proxies the request to the backend.
> 
> https://create-react-app.dev/docs/proxying-api-requests-in-development/ describes how our proxy setup will avoid CORS in your case with the local development environment.

Ah ok, so its avoiding CORS rather than being allowed through CORS. I see

**Comment by WaiHaiDere** [comment]
@ErnWong  does this mean that the CORS issue will have been fixed by #64

**Comment by ErnWong** [comment]
I think both have been fixed yeah. Now that I have access to a power plug, I'll have a try on my machine.

**Comment by ErnWong** [comment]
Yup - it works locally in my development environment (after tweaking some server and frontend so that the endpoints match)

**Comment by ErnWong** [comment]
Closing. Feel free to reopen or continue the conversation if needed.
