### ISSUE TITLE
Detailed post endpoint issue with a post with multiple comments.

### ISSUE THREAD

**Issue by kaplunket** [se701-group6/se701-assignment1#87]
Getting detailed post data for a post with more than one comment fails

## Expected Behavior

It should not throw an error and return the post with both comments

## Current Behavior

It throws a casting error

## Possible Solution

fix the casting issue

## Steps to Reproduce

1. create a post
2. add 2 comments
3. get detailed view of that post

**Comment by KimGyosu** [comment]
This is an bi issue and needs to be fixed immediately.
