### ISSUE TITLE
Improve backend test coverage

### ISSUE THREAD

**Issue by ErnWong** [se701-group6/se701-assignment1#91]
**Is your feature request related to a problem? Please describe.**
As a new developer unfamiliar to this codebase, I want a better backend API test coverage, so I can refactor and add new functionality to the backend safely without breaking the assumptions used in the frontend.

**Describe the solution you'd like**
@GrunWong  helped me identify that tests for these situations are lacking:

- [x] Update post API - missing title/body
- [x] Downvoting API - type = [invalid, sad, laugh]
- [x] Upvoting API - type = [sad, laugh]
- [x] Get single post API - id not found, and zero comments
- [x] Get all posts API
- [x] Comment unit test for model

Moreover, it would be good to:

- [x] Group the tests logically.

Related: Backend (and frontend) tests will need to be updated when we add the `/api` prefix to the endpoints as per #90.

**Describe alternatives you've considered**
Manual testing is error prone.

**Additional context**
Refer to the [API specs](https://github.com/se701-group6/se701-assignment1/wiki/API) for the behaviour that needs to be tested, and see the [integration](https://github.com/se701-group6/se701-assignment1/wiki/Backend#integration) and [unit testing guidelines](https://github.com/se701-group6/se701-assignment1/wiki/Backend#unit-tests-1).

**Comment by GrunWong** [comment]
I approve.

**Comment by timovv** [comment]
I approve

**Comment by kaplunket** [comment]
I approve
